### ISSUE TITLE
Create a script that alerts devs if dependencies are missing

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-local-dev#101]
This could be part of install or ./pm2 start somehow

**Comment by vladikoff** [comment]
This should verify that `redis`, `memcached` and `docker` are accessible

**Comment by deeptibaghel** [comment]
@vladikoff , should we check it at this point :
https://github.com/mozilla/fxa-local-dev/blob/ded51b7876e095672fb136457eab8eda4acd7c07/_scripts/install_all.sh#L51

**Comment by vladikoff** [comment]
@deeptibaghel let's make a new script and run it before 'install_all'
