### ISSUE TITLE
Add the pairing channel server to the list of servers to run

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-local-dev#129]
This repo: https://github.com/mozilla-services/pairsona/, the server to run is in https://github.com/mozilla-services/pairsona/tree/master/channelserver

**Comment by eoger** [comment]
Can I steal this @shane-tomlinson? I'm currently waiting on https://github.com/mozilla-services/pairsona/issues/23 to restart work on this.

**Comment by shane-tomlinson** [comment]
@eoger - sure, I didn't realize it was assigned to me!
