### ISSUE TITLE
should use HTTPs for fxa

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-local-dev#3]

**Comment by ravermeister** [comment]
but is it possible to change the settings in servers.json sothat all fx Servers communicate via https?

**Comment by vladikoff** [comment]
> but is it possible to change the settings in servers.json sothat all fx Servers communicate via https?

Should be possible yeap, content server has a setting to use https. might be possible to put nginx or something in front of the stack and forward requests through it to avoid tweaking configuraiton
