### ISSUE TITLE
npm test and npm start fails with "unhandled 'error' event"

### ISSUE THREAD

**Issue by maltris** [mozilla/fxa-local-dev#37]
After the installation of all dependencies and running the "npm install"-command, it fails with:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1000:11)
    at Process.ChildProcess._handle.onexit (child_process.js:791:34)
npm ERR! Test failed.  See above for more details.
 
npm ERR! not ok code 0

Here is the full output:

http://pastebin.com/nyrbJXpf

And here is the npm-debug.log:

http://pastebin.com/rTzCMSUM

Any idea? I'm pretty sure I followed the Readme very precisely. If you need further information, I will provide anything I can. :)

**Comment by vladikoff** [comment]
@maltris did you install the JDK https://github.com/mozilla/fxa-local-dev#functional-tests ?

**Comment by vladikoff** [comment]
Also you are saying:

> After the installation of all dependencies and running the "npm install"-command, it fails with:

but the pastebin is running:

`npm test`

**Comment by maltris** [comment]
>but the pastebin is running:

Sorry, my mistake. I meant npm test and npm start as seen in the paste. 

JDK is set up and "pm2 status" gives me a table as shown in the screenshot but displays only the first row (head). 

What is the distro mozilla is recommending/developing the Sync- and Accounts-Servers on?

I smell that node.js 0.10.29 is way too old because at installing some packages gave me warnings that they require >=0.10.40.

**Comment by vladikoff** [comment]
@maltris we work on it using Ubuntu and OS X.

> "pm2 status" gives me a table as shown in the screenshot but displays only the first row (head).

That means servers are probably not running. You should get this:

![](http://v14d.com/i/56095ad71d5c5.jpg)

**Comment by maltris** [comment]
Hello, i think this might be closed since you are not yet supporting anything than Ubuntu and OS X.

What i did:

- install a clean 14.04
- follow the instructions

Its now working and the servers are running. 

Thanks!

**Comment by vladikoff** [comment]
> i think this might be closed since you are not yet supporting anything else than Ubuntu and OS X.

What did you try it on?
