### ISSUE TITLE
"Unexpected error" on signup page

### ISSUE THREAD

**Issue by maltris** [mozilla/fxa-local-dev#38]
Hello,

recently im testing a bit around with the Accounts- and Sync-Servers. I got the servers up and running now, but when trying to sign up on the page, the "Sign up" button just turns grey and the red field "Unexpected error" appears.

I am willing to help as much as possible, so please tell me what logs from what process are necessary. (Or what else you need to dig into that.)

The setup was made on Ubuntu 14.04 according to the Readme. When running "./pm2 status" all servers are "online".

Screenshot of the error: http://i.imgur.com/Ib49YUb.png

Best regards

**Comment by vladikoff** [comment]
> Screenshot of the error: http://i.imgur.com/Ib49YUb.png

Need at least some information of the requests that are failing, try opening the developer tools and checking what request is failing

**Comment by maltris** [comment]
Hi!

You already closed this one? 

Heres the developer tools log-output:

http://i.imgur.com/3C31NuG.png

Here as text:

http://pastebin.com/UrnBXqgG

**Comment by vladikoff** [comment]
> You already closed this one?

Not a valid bug, the server is just not running.

From the screenshot, it means the auth server on http://127.0.0.1:9000 is not running properly. 
Navigate to that address and check to make sure it is running.

**Comment by maltris** [comment]
You are right. 

I checked the "pm2 status" and did not find a server on 9000. Then I did "netstat -tulp" to list all listening servers. Non was listening on 9000.

So I ran the installation process of the fxa-auth-server again, started it and now it is working.
