### ISSUE TITLE
Instructions on how to create developer account when working locally

### ISSUE THREAD

**Issue by mrjonny2** [mozilla/fxa-local-dev#49]
I cannot see how to activate a developer account for the console when working on the branch

**Comment by vladikoff** [comment]
@mrjonny2 Ah this is a tricky one, it is blocked by https://github.com/mozilla/fxa-oauth-server/issues/233 

To activate an account locally make sure to stop the OAuth server via `pm2` then start : 

https://github.com/mozilla/fxa-oauth-server in `DB=mysql` mode with mysql running locally

then make sure to start `internal.js` locally: https://github.com/mozilla/fxa-oauth-server/blob/master/bin/internal.js via `node bin/internal.js`

Let me know if you need more help.

**Comment by vladikoff** [comment]
@mrjonny2 lastly make sure that the developer account has a fake "@mozilla.com" email address, only that domain will let you in.

**Comment by mrjonny2** [comment]
is there a way to change the required domain from @mozilla.com to something else?

**Comment by vladikoff** [comment]
> is there a way to change the required domain from @mozilla.com to something else?

https://github.com/mozilla/fxa-oauth-server/blob/master/lib/config.js#L13

> Once I have it running as you have said, how do I actually activate the developer account?

It should be automatically activated if you have the oauth server server.js and internal.js running properly. where is it stuck?

**Comment by mrjonny2** [comment]
I changed the servers.json file to include the DB
```
    {
      "name": "oauth-server PORT 9010",
      "script": "bin/server.js",
      "cwd": "fxa-oauth-server",
      "env": {
        "NODE_ENV": "dev",
        "DB": "mysql"
      },
      "max_restarts": "1",
      "min_uptime": "2m"
    },
```

And then started everything as normal, then ran the node bin/internal.js for the internal server but I just get 
```
Jonnys-MacBook-Pro:fxa-oauth-server jonny_flowers$ node bin/internal.js 
{"Timestamp":1450471372593000000,"Logger":"fxa-oauth-server","Type":"server.clients.prod","Severity":6,"Pid":15745,"EnvVersion":"2.0","Fields":{"msg":"Disabling response schema validation"}}
{"Timestamp":1450471372606000000,"Logger":"fxa-oauth-server","Type":"db.ping","Severity":2,"Pid":15745,"EnvVersion":"2.0","Fields":{}}
{"Timestamp":1450471372607000000,"Logger":"fxa-oauth-server","Type":"bin.internal.db.ping","Severity":0,"Pid":15745,"EnvVersion":"2.0","Fields":{}}
Jonnys-MacBook-Pro:fxa-oauth-server jonny_flowers$ 
```
And when I try and login to the ouath console I get
```
Error: Developer cannot be validated or activated
```

I think it may be that I am not starting it up in SQL mode, I thought it would just be an env variable

**Comment by vladikoff** [comment]
@mrjonny2 you need `NODE_ENV=dev DB=mysql node bin/internal.js`

**Comment by vladikoff** [comment]
Added some docs here: https://github.com/mozilla/fxa-local-dev/blob/master/README.md#oauth-console-developer-accounts
