### ISSUE TITLE
pm2 kill doesn't stop neither fxa-content-server nor syncserver

### ISSUE THREAD

**Issue by jua-mp** [mozilla/fxa-local-dev#65]
After running ./pm2 kill I always have to kill two process manually.

Here the output of ps ax after running ./pm2 kill
```
7683 ?        Sl     0:00 /home/fxa/fxa-local-dev/syncserver/local/bin/python2 ./local/bin/pserve ../_scripts/syncserver.ini
8204 ?        Sl     0:01 node /home/fxa/fxa-local-dev/fxa-content-server/server/bin/fxa-content-server.js`
```
This is just slightly annoying so it is not a big issue. It nevertheless causes the syncserver to fail while starting again, as there is already a server listening on the socket when it tries to bind to it.

Also, I am not sure of this should be filed against pm2 directly or if it has to do with how the processes are set up in the first place.

Possibly useful information:
- nodejs version v4.3.1
- npm 1.4.21
- pm2 version 0.15.10

Anyway, thank you very much! :smile:

**Comment by vladikoff** [comment]
yea we should wrap the sync server into a killable node script.

However I cannot reproduce this for the content server

**Comment by shane-tomlinson** [comment]
> However I cannot reproduce this for the content server

I can, 99% of the time. 1% of the time it works.

**Comment by shane-tomlinson** [comment]
> However I cannot reproduce this for the content server

I've gone so far as to create this script to restart the content server:

```bash
#!/bin/bash

NODE_PID=`ps ax | grep node | grep fxa-content-server | awk '{print $1}'`
kill "${NODE_PID}"
```

**Comment by jua-mp** [comment]
> However I cannot reproduce this for the content server

I have been using a script that kills both processes for a long time, so I cannot really tell how often it happens, although I did have the feeling that it was *all* the time.

>I've gone so far as to create this script to restart the content server:

I had one too, but it was far less elegant than yours and would mercilessly kill all my node processes:
```
#!/bin/bash

pkill node
```
I'll certainly start using yours :+1:

**Comment by jua-mp** [comment]
>>However I cannot reproduce this for the content server

> I have been using a script that kills both processes for a long time, so I cannot really tell how often it happens, although I did have the feeling that it was all the time.

@vladikoff: I cannot reproduce it any longer. I am sure it was like that at some point, but it doesn't happen any more. I have reinstalled the whole fxa-local-dev with all its servers pretty often and have used my script blindly since it first happened so I cannot really tell when it started working again.

**Comment by vbudhram** [comment]
@jua-mp I was having a similar issue, but upgrading to pm2 1.1.3 seemed to fix it for me.

**Comment by jua-mp** [comment]
@vbudhram Thank you very much!

Nonetheless, it is explicitly defined as `"pm2": "0.15.10"` in the `fxa-local-dev/package.json`

Does anybody know if there is a reason for this?

**Comment by philbooth** [comment]
@philbooth NOTE TO SELF, do what Vijay did
