### ISSUE TITLE
  _scripts/postinstall.sh doesn't work on my system

### ISSUE THREAD

**Issue by Anh3h** [mozilla/fxa-local-dev#69]
Am a new developer looking to contribute to this software but   _scripts/postinstall.sh doesn't seem to run on my system.
Am using => 
    Ubuntu 16.04
    nodejs v4.2.6
    npm v3.5.2

Here is the error that displays on my terminal: 
_scripts/install_all.sh: line 36: cd: fxa-content-server: No such file or directory

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! fxa-local-dev@1.0.2 postinstall: `_scripts/postinstall.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fxa-local-dev@1.0.2 postinstall script '_scripts/postinstall.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fxa-local-dev package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     _scripts/postinstall.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fxa-local-dev
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fxa-local-dev
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/courage/fxa-local-dev/npm-debug.log

Someone please help me

**Comment by rfk** [comment]
>  _scripts/install_all.sh: line 36: cd: fxa-content-server: No such file or directory

This sounds like it failed to clone one of the repos, do you have any additional error output from before that line?

**Comment by Anh3h** [comment]
yes
A bunch of fatal error:

error: RPC failed; curl 35 gnutls_handshake() failed: Error in the pull function.
fatal: The remote end hung up unexpectedly
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
...
error: RPC failed; curl 28 Operation timed out after 0 milliseconds with 0 out of 0 bytes received
fatal: The remote end hung up unexpectedly

**Comment by rfk** [comment]
Yikes!  Looks like network-related issues of some kind.

Are you able to clone the repo by hand, using the commands at https://github.com/mozilla/fxa-local-dev/blob/master/_scripts/install_all.sh#L8 ?

**Comment by Anh3h** [comment]
ohhh u mean manually
 i can but ...

fxa-local-dev$ npm install
npm WARN deprecated cross-spawn-async@2.2.1: cross-spawn no longer requires a build toolchain, use it instead!
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated URIjs@1.16.1: package renamed to "urijs" (lower-case), please update accordingly
npm WARN prefer global coffee-script@1.10.0 should be installed with -g

> fxa-local-dev@1.0.2 postinstall /home/courage/fxa-local-dev
> _scripts/postinstall.sh

+ _scripts/install_all.sh
+ ulimit -S -n 2048
+ git clone https://github.com/mozilla/fxa-content-server.git
+ git clone https://github.com/mozilla/fxa-content-server-l10n.git
+ git clone https://github.com/mozilla/fxa-auth-server.git
+ git clone https://github.com/mozilla/fxa-customs-server.git
+ git clone https://github.com/mozilla/fxa-basket-proxy.git
Cloning into 'fxa-content-server'...
+ wait
+ git clone https://github.com/mozilla/fxa-auth-db-mysql.git
+ git clone https://github.com/mozilla/fxa-auth-mailer.git
Cloning into 'fxa-content-server-l10n'...
Cloning into 'fxa-customs-server'...
Cloning into 'fxa-auth-server'...
Cloning into 'fxa-auth-mailer'...
+ git clone https://github.com/vladikoff/browserid-verifier.git -b http
+ git clone https://github.com/mozilla/fxa-oauth-server.git
+ git clone https://github.com/mozilla/fxa-oauth-console.git
Cloning into 'fxa-basket-proxy'...
Cloning into 'fxa-auth-db-mysql'...
+ git clone https://github.com/mozilla/fxa-profile-server.git
+ git clone https://github.com/mozilla-services/syncserver.git
Cloning into 'fxa-oauth-server'...
+ git clone https://github.com/mozilla/123done.git -b oauth
Cloning into 'fxa-oauth-console'...
Cloning into 'fxa-profile-server'...
Cloning into 'syncserver'...
Cloning into '123done'...
Cloning into 'browserid-verifier'...
remote: Counting objects: 314, done.
remote: Compressing objects: 100% (4/4), done.
remote: Counting objects: 300, done.
remote: Counting objects: 29756, done.
remote: Counting objects: 697, done.
remote: Counting objects: 1110, done.
remote: Counting objects: 1880, done.
remote: Counting objects: 2883, done.
remote: Counting objects: 1961, done.
remote: Compressing objects: 100% (8/8), done.
remote: Counting objects: 1358, done.
remote: Counting objects: 1057, done.
remote: Compressing objects: 100% (4/4), done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 300 (delta 0), reused 0 (delta 0), pack-reused 300
Receiving objects: 100% (300/300), 57.74 KiB | 13.00 KiB/s, done.
Resolving deltas: 100% (158/158), done.
Checking connectivity... done.110)   
remote: Compressing objects: 100% (49/49), done.
remote: Counting objects: 12076, done.
remote: Compressing objects: 100% (199/199), done.
remote: Total 314 (delta 0), reused 0 (delta 0), pack-reused 310
Receiving objects: 100% (314/314), 359.22 KiB | 20.00 KiB/s, done.
Resolving deltas: 100% (168/168), done.00 KiB | 8.00 KiB/s   
remote: Total 697 (delta 0), reused 0 (delta 0), pack-reused 697
Checking connectivity... done.883), 204.01 KiB | 12.00 KiB/s   
Receiving objects: 100% (697/697), 185.84 KiB | 2.00 KiB/s, done.
Resolving deltas: 100% (404/404), done.
Checking connectivity... done.1358), 356.00 KiB | 4.00 KiB/s   
remote: Total 1358 (delta 21), reused 0 (delta 0), pack-reused 1309
Receiving objects: 100% (1358/1358), 481.19 KiB | 2.00 KiB/s, done.
Resolving deltas: 100% (837/837), done.
Checking connectivity... done.
error: RPC failed; curl 35 gnutls_handshake() failed: Error in the pull function.
fatal: The remote end hung up unexpectedly
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
remote: Total 1961 (delta 1), reused 0 (delta 0), pack-reused 1953
Receiving objects: 100% (1961/1961), 862.72 KiB | 8.00 KiB/s, done.
Resolving deltas: 100% (1069/1069), done.
Checking connectivity... done.
remote: Total 1057 (delta 0), reused 0 (delta 0), pack-reused 1053
Receiving objects: 100% (1057/1057), 2.62 MiB | 75.00 KiB/s, done.
Resolving deltas: 100% (509/509), done.
Checking connectivity... done.
error: RPC failed; curl 28 Operation timed out after 0 milliseconds with 0 out of 0 bytes received
fatal: The remote end hung up unexpectedly
+ cd fxa-content-server
_scripts/install_all.sh: line 36: cd: fxa-content-server: No such file or directory

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! fxa-local-dev@1.0.2 postinstall: `_scripts/postinstall.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fxa-local-dev@1.0.2 postinstall script '_scripts/postinstall.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fxa-local-dev package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     _scripts/postinstall.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fxa-local-dev
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fxa-local-dev
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/courage/fxa-local-dev/npm-debug.log
 
There you FINE COMPLETE process of everything that happen so i thought all the necessary cloning took place

**Comment by rfk** [comment]
I'm not sure what to do about the TLS/network error here, but in addition, it seems that install_all.sh should fail with an error when it fails to clone one of the repos, rather than continuing and trying to use the checked-out directories.  That seems like a bug in the script itself.

@Anh3h you could try editing https://github.com/mozilla/fxa-local-dev/blob/master/_scripts/install_all.sh so that it runs each `git clone` in the foreground, rather than backgrounding them all to run in parallel.  In other words, remove the trailing ` &` from all of the `git clone` lines in that file, and see if that helps it run the completion.

**Comment by Anh3h** [comment]
i did that but i got the same error in thesame file:

_scripts/install_all.sh: line 36: cd: fxa-content-server: No such file or directory

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! fxa-local-dev@1.0.2 postinstall: `_scripts/postinstall.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fxa-local-dev@1.0.2 postinstall script '_scripts/postinstall.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fxa-local-dev package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     _scripts/postinstall.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fxa-local-dev
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fxa-local-dev
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by Anh3h** [comment]
i opened the file ''install_all.sh" and did the installation manually since all the repos to be cloned had already cloned but i got an error when i tried running:

cd fxa-auth-server; npm i; node ./scripts/gen_keys.js; cd ..

error:
npm ERR! git clone --template=/home/courage/.npm/_git-remotes/_templates --mirror https://github.com/mozilla/fxa-auth-mailer.git /home/courage/.npm/_git-remotes/git-https-github-com-mozilla-fxa-auth-mailer-git-5bb87c67faab406f96e5bcfad62693ad396efe0e-f1fdfc43: Cloning into bare repository '/home/courage/.npm/_git-remotes/git-https-github-com-mozilla-fxa-auth-mailer-git-5bb87c67faab406f96e5bcfad62693ad396efe0e-f1fdfc43'...
npm ERR! git clone --template=/home/courage/.npm/_git-remotes/_templates --mirror https://github.com/mozilla/fxa-auth-mailer.git /home/courage/.npm/_git-remotes/git-https-github-com-mozilla-fxa-auth-mailer-git-5bb87c67faab406f96e5bcfad62693ad396efe0e-f1fdfc43: fatal: unable to access 'https://github.com/mozilla/fxa-auth-mailer.git/': Empty reply from server
npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/courage/.npm/_git-remotes/_templates --mirror https://github.com/mozilla/fxa-auth-mailer.git /home/courage/.npm/_git-remotes/git-https-github-com-mozilla-fxa-auth-mailer-git-5bb87c67faab406f96e5bcfad62693ad396efe0e-f1fdfc43
npm ERR! Cloning into bare repository '/home/courage/.npm/_git-remotes/git-https-github-com-mozilla-fxa-auth-mailer-git-5bb87c67faab406f96e5bcfad62693ad396efe0e-f1fdfc43'...
npm ERR! fatal: unable to access 'https://github.com/mozilla/fxa-auth-mailer.git/': Empty reply from server
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/courage/fxa-local-dev/fxa-auth-server/npm-debug.log
module.js:328
    throw err;
    ^

Error: Cannot find module 'envc'
    at Function.Module._resolveFilename (module.js:326:15)

**Comment by Anh3h** [comment]
continuation ...

at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/courage/fxa-local-dev/fxa-auth-server/config/index.js:5:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

**Comment by Anh3h** [comment]
Well managed to get that line of code running but other errors displayed ... so i cann't even run this line. get the following error:
npm ERR! Failed at the fxa-oauth-server@0.70.0 postinstall script 'node scripts/gen_keys'.

**Comment by Anh3h** [comment]
system works now perfectly. No really sure what i did. but I manually did the installation for all the repos cloned
