### ISSUE TITLE
Firefox local sever crashes when i try to siginin to my firefox account

### ISSUE THREAD

**Issue by Anh3h** [mozilla/fxa-local-dev#70]
when i run my fxa local sever it workes and my lgin page opens on my browser fine but when try signing in to my firefox account the page doesn't open and my ./pm2 status becomes ;
 App name                                       │ id │ mode │ pid   │ status  │ restart │ uptime │ memory       │ watching │
├────────────────────────────────────────────────┼────┼──────┼───────┼─────────┼─────────┼────────┼──────────────┼──────────┤
│ auth-server local mail helper                  │ 0  │ fork │ 0     │ errored │ 0       │ 0      │ 0 B          │ disabled │
│ auth-server db memory                          │ 1  │ fork │ 8955  │ online  │ 0       │ 2m     │ 39.727 MB    │ disabled │
│ auth-server key server PORT 9000               │ 2  │ fork │ 0     │ errored │ 0       │ 0      │ 0 B          │ disabled │
│ content-server PORT 3030                       │ 3  │ fork │ 10643 │ online  │ 2       │ 8s     │ 159.188 MB   │ disabled │
│ fxa-basket-proxy PORT 1114                     │ 4  │ fork │ 0     │ errored │ 0       │ 0      │ 0 B          │ disabled │
│ fxa-basket-proxy fake basket server PORT 10140 │ 5  │ fork │ 0     │ errored │ 0       │ 0      │ 0 B          │ disabled │
│ oauth-server PORT 9010                         │ 6  │ fork │ 0     │ errored │ 0       │ 0      │ 0 B          │ disabled │
│ oauth-server-internal PORT 9011                │ 7  │ fork │ 0     │ errored │ 0       │ 0      │ 0 B          │ disabled │
│ profile-server PORT 1111                       │ 8  │ fork │ 0     │ errored │ 0       │ 0      │ 0 B          │ disabled │
│ profile-server static dev PORT 1112            │ 9  │ fork │ 0     │ errored │ 0       │ 0      │ 0 B          │ disabled │
│ profile-server worker PORT 1113                │ 10 │ fork │ 0     │ errored │ 0       │ 0      │ 0 B          │ disabled │
│ 123done PORT 8080                              │ 11 │ fork │ 9041  │ online  │ 0       │ 2m     │ 51.941 MB    │ disabled │
│ 321done UNTRUSTED PORT 10139                   │ 12 │ fork │ 9056  │ online  │ 0       │ 2m     │ 57.410 MB    │ disabled │
│ fxa-oauth-console PORT 10137                   │ 13 │ fork │ 9068  │ online  │ 0       │ 2m     │ 22.254 MB    │ disabled │
│ browserid-verifier PORT 5050                   │ 14 │ fork │ 9074  │ online  │ 0       │ 2m     │ 30.699 MB    │ disabled │
│ sync server PORT 5000                          │ 15 │ fork │ 9108  │ online  │ 0       │ 2m     │ 2.887 MB     │ disabled │
│ auth-mailer PORT 10136                         │ 16 │ fork │ 0     │ errored │ 0       │ 0      │ 0 B          │ disabled │

Some one please help me!!!

**Comment by vladikoff** [comment]
Hey, @Anh3h, seems like there were issues with installation. make sure you are using node 4.5 or node 4.6.

 do you want to try using the `npm run start-remote` command instead of using fxa-local-dev?
