### ISSUE TITLE
 auth-server key server fails instantly

### ISSUE THREAD

**Issue by tiiigra** [mozilla/fxa-local-dev#71]
When I  start the servers with `./pm2 start servers.json`command the status log looks just fine, but auth-server key server  fails the next moment and  `./pm2 status`  reports error status.  I can't sign up for an account as well.

I am running Ubuntu 16.04 with nodejs 4.6.0, npm 2.4.1, Python  2.7.12 installed. Other dependencies like  Redis, libgmp, graphicsmagick are installed either.

Any help with setting up the project is appreciated!

**Comment by vbudhram** [comment]
Hey @tiiigra you could try using the auth-server directly (`npm start` from fxa-auth-server directory) to verify that it is installed correctly and there are no port conflicts. Before running, I usually make sure that all node processes have been killed.

**Comment by tiiigra** [comment]
So I cloned fxa-local-dev again and it turned out that there are issues with `node-gyp` configure build. 

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/tiigra/node-v4.6.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-38-generic
command "/home/tiigra/node-v4.6.0-linux-x64/bin/node" "/home/tiigra/node-v4.6.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/tiigra/fxa-local-dev/browserid-verifier/node_modules/browserid-local-verify/node_modules/browserid-crypto/node_modules/bigint
gyp ERR! node -v v4.6.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
```

**Comment by vbudhram** [comment]
@tiiigra Looks like you are using an outdated version of npm. Node 4.6 ships with npm 2.15 if you want to try that. Closing until further notice.
