### ISSUE TITLE
every time I start the servers, the oauth console is loaded

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-local-dev#74]
@philbooth noticed this too.

Every time I start the servers, the OAuth console is brought up in the browser.

STR:

```bash
npm start servers.json
```

**Comment by vbudhram** [comment]
Noticed this too. Look's like it is launched from [here](https://github.com/mozilla/fxa-oauth-console/blob/master/scripts/run_dev.js#L23). We could add an env in there to auto launch browser and then set in `server.json`.

**Comment by vladikoff** [comment]
this is due https://github.com/mozilla/fxa-local-dev/commit/eb522918f6ca472b51ef82f829a03a1b7ee973f0 , will investigate ...

**Comment by vladikoff** [comment]
Fixed in https://github.com/mozilla/fxa-oauth-console/commit/48c14e9c9604498d19100eb65e1819862c4596dc
