### ISSUE TITLE
Should the README say to install Java 8?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-local-dev#81]
The [README.md file](https://github.com/mozilla/fxa-local-dev/tree/cef6efe1bdab1e8da6cd17a9623293a51250d771) says to install [Java 7](https://github.com/mozilla/fxa-local-dev/tree/cef6efe1bdab1e8da6cd17a9623293a51250d771#ubuntu-1), yet running hte functional tests using geckodriver needs Java 8 IIRC.

cc @vladikoff

**Comment by vladikoff** [comment]
yea!

**Comment by vladikoff** [comment]
need to add some instructions for ubuntu, and maybe os x
