### ISSUE TITLE
'brew install yarn' overrides nvm

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-local-dev#86]
from eoger:

the problem is it installs node (because it's a dependency) on top of the version nvm

**Comment by eoger** [comment]
I'm not sure how bad this is, but I was kinda surprised when opening a new tab, typing `node --version` and not getting the expected `zsh: command not found: node`

**Comment by vladikoff** [comment]
Removed yarn, just gonna switch to npm@5 when it is time
