### ISSUE TITLE
Add Docker helper servers

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-local-dev#94]
Local docker containers that would be nice:

- [x] Local MySQL Server
- [x] Local SQS / SNS Fake server (something like https://github.com/p4tin/goaws)
- [x] Use the Docker version of the Sync Server
- [x] Maybe move redis into this container too
- [x] Memcached
- [x] Others???

**Comment by vladikoff** [comment]
Should use https://docs.docker.com/docker-for-mac/ on Mac and the CLI or something on Linux

**Comment by philbooth** [comment]
memcached for the customs and auth servers?

**Comment by vladikoff** [comment]
> memcached for the customs and auth servers?

Yessss!

**Comment by vladikoff** [comment]
A good starting point for this would jus be adding `memcached` (same as we have redis)

**Comment by deeptibaghel** [comment]
@vladikoff I haven't created docker container earlier but i am willing to learn and work on this.

**Comment by vladikoff** [comment]
@deeptibaghel some notes for this,

for the `Local SQS / SNS Fake server` part we need the following:

0. add docs that now docker is a dependency. I assume OS X will use this https://docs.docker.com/docker-for-mac/install/ and Linux will probably a simpler install
1. create a `.js` file like https://github.com/mozilla/fxa-local-dev/blob/master/_scripts/memcached.js
  on start it should run `docker run -d --name goaws -p 4100:4100 pafortin/goaws`
2. when we call `./pm2 kill` or `./pm2 kill [id_of_goaws_process]` it should run `docker stop` on that container Ref: https://docs.docker.com/engine/reference/commandline/stop/

Part of final testing for this would be testing this: https://github.com/mozilla/fxa-content-server/issues/5433 (with all local servers running, inside content server repo we would run: `npm run test-functional -- --grep="opt-in on signup"). Currently that tests fails because we don't have SQS/SNS running locally. (this is what we are trying to fix in this part of the issue)

**Comment by deeptibaghel** [comment]
Thanks a lot @vladikoff :)

**Comment by deeptibaghel** [comment]
@vladikoff , i am getting error from this line as of now :
https://github.com/mozilla/fxa-basket-proxy/blob/47fe2eb243878b185f44ec0d4d258a3b59064a43/lib/basket/fake.js#L54

I am not clear, how do we get "userData" at this point if it is not yet initialized.

**Comment by vladikoff** [comment]
@deeptibaghel see this https://github.com/mozilla/fxa-auth-server/blob/81700dae04777187b7ba5a687b9a036a14d06888/config/index.js#L442-L447

**Comment by vladikoff** [comment]
@deeptibaghel also see this https://github.com/mozilla/fxa-basket-proxy/blob/master/lib/config.js#L82 

so in the `goaws` you need to subscribe one of the SQS Queues to an SNS Topic. I think there should be some pre-made already in `goaws`. Anyway, if something is not working just send the PR that starts `goaws` to this repository and we will go from there :)

**Comment by vladikoff** [comment]
@deeptibaghel next thing we should do for this bug is:

Use the sync server docker container. Currently we do this:

```
    {
      "name": "sync server PORT 5000",
      "script": "../_scripts/syncserver.sh",
      "cwd": "syncserver",
      "max_restarts": "1",
      "min_uptime": "2m"
    },
```

Can we replace that with https://github.com/mozilla-services/syncserver/#runner-under-docker

**Comment by vladikoff** [comment]
@deeptibaghel for now we can copy paste the script that we already have for `goaws` but at some point we might be able to make that script generic, so we can reuse it for other containers

**Comment by deeptibaghel** [comment]
@vladikoff yeah sure

**Comment by vladikoff** [comment]
@deeptibaghel i noticed if the docker vm is not running then I get an error:

```
/Users/vladikoff/.pm2/logs/Fake-SQS-SNS-PORT-4100-error-17.log last 10 lines:
17|Fake SQ | See 'docker run --help'.
17|Fake SQ | "docker stop" requires at least 1 argument(s).
17|Fake SQ | See 'docker stop --help'.
17|Fake SQ | 
17|Fake SQ | Usage:  docker stop [OPTIONS] CONTAINER [CONTAINER...]
17|Fake SQ | 
17|Fake SQ | Stop one or more running containers
17|Fake SQ | Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
17|Fake SQ | docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
17|Fake SQ | See 'docker run --help'.
```

But i still get status online:

![image](https://user-images.githubusercontent.com/128755/38519458-e8727614-3c0d-11e8-86f4-73cb3ffede50.png)

We might have hook into the exit status of the docker start

**Comment by deeptibaghel** [comment]
@vladikoff , so the error is because we are trying to stop , non running container ?
Adding the fix for the same.

**Comment by vladikoff** [comment]
> so the error is because we are trying to stop , non running container ?

The error is because I don't have the docker VM running. For example on a mac, if you don't have the app running then the commands will fail:

![image](https://user-images.githubusercontent.com/128755/38561170-54a333f4-3ca5-11e8-9c38-59be0bb117f9.png)

**Comment by vladikoff** [comment]
@deeptibaghel for the next thing let's add a MySQL  and a Redis container. @jbuck will confirm which version to use it was version  5.6.21 in the past

**Comment by vladikoff** [comment]
5.6.21  of MySQL that is

**Comment by jbuck** [comment]
We're currently using 5.6.34 in production but I'd recommend using the 5.6 tag for the latest in the 5.6.x series

**Comment by deeptibaghel** [comment]
Sure @vladikoff , @jbuck  :)
