### ISSUE TITLE
browserid-verifier failure causes the entire install to fail

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-local-dev#95]
I just had to set up `fxa-local-dev` from scratch and the install failed because of something something browserid-verifier.

I didn't really care about that part but wanted the rest of the install to work, so I manually copied the remaining steps from `_scripts/install_all.sh` and continued on my merry way. It was kind of annoying.

I'm not sure if that counts as an issue, feel free to close this if not.

**Comment by vladikoff** [comment]
@philbooth need the log :( 

browserid-verifier install can sometimes look very bad but actually succeed 🗡

**Comment by philbooth** [comment]
> need the log

Okey doke, I'll have another bash at it tomorrow!

**Comment by philbooth** [comment]
> browserid-verifier install can sometimes look very bad but actually succeed 🗡

Also meant to say: fwiw, that's not what happened here. The install failed, there was no `./pm2` symlink created, and none of the following repos (oauth, profile, etc) were cloned.

(I'll grab the logs as soon as I'm back on my other machine)

**Comment by vladikoff** [comment]
We made some updates since and this should be better now
