### ISSUE TITLE
Cloning Git repos behind Firewall

### ISSUE THREAD

**Issue by eku** [mozilla/fxa-local-dev#96]
```npm i --production``` fails to clone the bare repos. It should use protocol ```https``` instead of ```git```. Git is often blocked by company firewalls.

Please adjust the URLs in the skripts. Thanks.

**Comment by vladikoff** [comment]
Probably won't be supporting this edge case at this time. You can try something like:

```
git config --global url."https://".insteadOf git://
```

to avoid this issue if `git://` is blocked in your environment.

**Comment by eku** [comment]
@vladikoff While this might be an acceptable work-arond for the moment it has side effects on other git repos that require ```git://``` (i.e. inside company).

What's the reason for accessing public git repos anonymously with ```git://```?

Will you accept a PR?
